### ISSUE TITLE
Redstone wire uses cobweb texture

### ISSUE THREAD

**Issue by caleb39411** [Vogtinator/crafti#11]
As in title; also it doesn't seem to carry a redstone signal. This is running on Ndless for OS 5.2.0.771 on a TI-Nspire CX II-T.

**Comment by Vogtinator** [comment]
Yeah, the redstone wire here is actually 3d and doesn't attach to surfaces.

What's the structure you built? Can you make a screenshot?

**Comment by caleb39411** [comment]
Looking at it more closely, it seems it is the redstone texture with no colour added, and not flat, such that is resembles a cobweb.
I'm currently using a version I've compiled myself, but with the real minecraft textures, but this does occur in the latest release.
![IMG_20210108_220334](https://user-images.githubusercontent.com/16021499/104069952-af075080-51fd-11eb-9a43-cd7d5d515873.jpg)

**Comment by caleb39411** [comment]
Trying again, it seems to carry a signal, I don't know what I did the first time, but it only turns red when there is a signal going through it, and white otherwise.

**Comment by Vogtinator** [comment]
Yep - works as intended! Patches to improve the appearance and behaviour are welcome.
