### ISSUE TITLE
Scrollable inventory

### ISSUE THREAD

**Issue by m-doescode** [Vogtinator/crafti#16]
Hi,

Thank you once again for the help last time! I am forever grateful.

Anyway, I realize that it seems all the inventory slots have been taken up, prevent any new blocks.
Whether this is a good thing or not, I've forked the repo and added a new branch [scrolling-inventory](https://github.com/m-doescode/crafti-fork/tree/scrolling-inventory). It adds a new feature, if the player keeps pressing down, the inventory scrolls down, and vice versa.

Do you think this is a good idea? Should there be more slots or are the ones currently available good enough? Is there anything else I should add or is it due for a redesign.

It's not complete yet. For one, there is no indication of more slots yet so users have no idea there is more.
But before I continue further, I must ask for your opinion.

If you think this is a good idea, I will be happy to open a pull request.

Thanks, M.

**Comment by Vogtinator** [comment]
Hi! Yes, something like this is necessary if new blocks get added, but currently it fits nicely so there's not much point in doing so yet.

Scroll indicators (arrows up and down at the right side) would definitely be necessary for discoverability.

**Comment by m-doescode** [comment]
> Hi! Yes, something like this is necessary if new blocks get added, but currently it fits nicely so there's not much point in doing so yet.

I thought so, the only reason I made this was because in my fork (not that it will ever be pushed upstream) I wanted to add stairs, but there was not enough space. But I thought it could still be useful for the main repo. But yeah, until more blocks are added, it is kind of useless.
 
> Scroll indicators (arrows up and down at the right side) would definitely be necessary for discoverability.

That I will do, I was also thinking of having the last row be only half shown, to imply there is more by going down.

**Comment by m-doescode** [comment]
Thank you for the feedback!
