### ISSUE TITLE
Questions regarding source and float alternative

### ISSUE THREAD

**Issue by Bluebotlabz** [Vogtinator/crafti#17]
I'm trying to add some new blocks to crafti and a few other QOL improvements, I was wondering how the special block textures are managed, especially with `special_block_texture_idx`?

Additionally, I was wondering if it would be possible to use fixed point numbers as they would give benefits of floating point numbers, but without the requirement of a FPU and would also give similar performance to current fixed-width integers (in theory?

Also, what exactly does enabling `#define BETTER_PERSPECTIVE` do?

**Comment by Vogtinator** [comment]
> Thanks! Do you think that a quality improvement could be achieved via increasing the width of the fixed point numbers or not?

They're 32bit, so the next step would not fit into a single register anymore. In places where it matters the fractional part is already tuned a bit.

**Comment by Bluebotlabz** [comment]
forgot that these calculators are only 32bit

**Comment by Bluebotlabz** [comment]
> > I'm trying to add some new blocks to crafti and a few other QOL improvements, I was wondering how the special block textures are managed, especially with `special_block_texture_idx`?
> 
> Blocks which use `renderSpecialBlock` do rendering themselves, they manage the textures themselves in a block specific way. Some use the terrain texture, some use other texture sources.
> 
> The particle effects when destroying blocks are textured with an area from the main terrain texture. For special blocks there are some (creative) assignments through `special_block_texture_idx`. It's not used in any other way currently.
> 
> > Additionally, I was wondering if it would be possible to use fixed point numbers as they would give benefits of floating point numbers, but without the requirement of a FPU and would also give similar performance to current fixed-width integers (in theory?
> 
> Crafti uses fixed point throughout as `GLFix`, through the `Fix` template.
> 
> > Also, what exactly does enabling `#define BETTER_PERSPECTIVE` do?
> 
> Switch from using fixed point to floating point for the perspective divide. That way there's more range and precision available, but with c9696de059fad9b575596ee41af993aab56a397c it's not that much of a difference anymore.

I can't seem to find the commit you mention, could you please let me know what was changed in it?

**Comment by Bluebotlabz** [comment]
also, just wondering, for special blocks, why is there a gap between the ids 135-146?

**Comment by Vogtinator** [comment]
The commit is in nGL, https://github.com/Vogtinator/nGL/commit/c9696de059fad9b575596ee41af993aab56a397c

> also, just wondering, for special blocks, why is there a gap between the ids 135-146?

I don't remember. It's not unlikely that I just mistyped 136 -> 146.

**Comment by Bluebotlabz** [comment]
Thank you
