### ISSUE TITLE
Special Block Data?

### ISSUE THREAD

**Issue by Bluebotlabz** [Vogtinator/crafti#19]
I'm wondering how special block data is handled?

I can see that they use some sort of bit-shift system to store block side and whatnot, but how exactly does this work?
And other than block-side is any other data sent to blocks?

I basically just want to know how blocks are represented in terms of binary and how that works? Like what bits are used for what data.
Thanks.

**Comment by m-doescode** [comment]
If I remember correctly, the first 8 bits represents block type, and the last 8 bits block data.

For block sides, a bit mask is used which filters out all bits except for the block side

**Comment by Bluebotlabz** [comment]
That makes sense, but which bits are for the block side?
(I decided to try to make cake edible, everything but block data seems to work)

**Comment by Bluebotlabz** [comment]
I'm also guessing that the gap between special IDs 135-146 are for binary purposes?

**Comment by m-doescode** [comment]
> That makes sense, but which bits are for the block side? (I decided to try to make cake edible, everything but block data seems to work)

The first 3 bits are used. But you should probably be using BLOCK_SIDE_BITS. Look in doorrenderer.cpp for an example

**Comment by m-doescode** [comment]
> I'm also guessing that the gap between special IDs 135-146 are for binary purposes? (wait nevermind, still no idea why it has that)

This, I have no idea why. For some reason the first 127 tupes are reserved for plain blocks and there other half is reserved for special block types

**Comment by Bluebotlabz** [comment]
> > That makes sense, but which bits are for the block side? (I decided to try to make cake edible, everything but block data seems to work)
> 
> The first 3 bits are used. But you should probably be using BLOCK_SIDE_BITS. Look in doorrenderer.cpp for an example

Yeah, I just wanted to make sure I wasn't overwriting anything important
Also, I'm working on _full docs_ of the code in my repo's wiki

**Comment by m-doescode** [comment]
> Also, I'm working on full docs of the code in my repo's wiki

Oh, that's nice! That would actually be pretty helpful.

**Comment by Bluebotlabz** [comment]
When you say first 3 bits, you mean right-to-left right?

So like:
0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1

Because I thought that was reserved for block type

**Comment by Bluebotlabz** [comment]
> > Also, I'm working on full docs of the code in my repo's wiki
> 
> Oh, that's nice! That would actually be pretty helpful.

https://github.com/Bluebotlaboratories/crafti/wiki
Feel free to help if you really want to try
(So much code and I'm not _that_ good at C++ overall)

**Comment by m-doescode** [comment]
> When you say first 3 bits, you mean right-to-left right?
> 
> So like: 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
> 
> Because I thought that was reserved for block type

I meant of the block data. I have no idea of its from the left or the right (I will research this later) but it definitely starts after 8 bits. Something like

0000 0000 1110 0000
Or
0000 0000 0000 0111

**Comment by Bluebotlabz** [comment]
Should we continue this discussion on my repo?

**Comment by m-doescode** [comment]
> Should we continue this discussion on my repo?

Probably. Also, maybe you could enable the discussions tab and continue it there?

**Comment by Bluebotlabz** [comment]
yep
done
(under the Q&A section)

**Comment by Bluebotlabz** [comment]
@m-doescode Forget that, moved it to general

**Comment by Vogtinator** [comment]
Every block is stored as 16 bits (`BLOCK_WDATA`), the lower 8 bits are the block number and the higher 8 bits the data, which is specific to each block.

In previous releases, the high bit of the data of every block (independent of the type) determined whether the block was redstone powered, but after the redstone rewrite that is no longer the case. For compatibility with existing maps, this bit is currently ignored for non-redstone blocks.

**Comment by Bluebotlabz** [comment]
Ok, thanks!
