### ISSUE TITLE
Teacher Software trial  3.9.0.463  won't run crafti

### ISSUE THREAD

**Issue by mstram** [Vogtinator/crafti#2]
When I try to use Open Document on  crafti.prg.tns, I am getting :

This document format is not supported

This happens with either the latest "Redstone Update" release or from
http://www.ticalc.org/archives/files/fileinfo/460/46054.html

**Comment by Vogtinator** [comment]
It's a program written in assembly so it requires either an appropriate emulator (nspire_emu) or an handheld to run it, you can't use the computer software.
