### ISSUE TITLE
"TI-Nspire CX II, TI- Nspire CX CAS II" has "64 MB of RAM, 100 MB of Flash ROM" and "ARM9 @ 396 MHz CPU" Please make an upgraded version that makes use of this extra power!

### ISSUE THREAD

**Issue by ShadowDrago855** [Vogtinator/crafti#24]
"TI-Nspire CX II, TI- Nspire CX CAS II" has "64 MB of RAM, 100 MB of Flash ROM" and "ARM9 @ 396 MHz CPU" Please make an upgraded version that makes use of this extra power!

**Comment by ShadowDrago855** [comment]
This calculator also supports Python!

**Comment by Vogtinator** [comment]
FYI, the CX also has 64MiB of RAM and 128MiB flash.
