### ISSUE TITLE
It said the file format is not supported

### ISSUE THREAD

**Issue by Cheoo21** [Vogtinator/crafti#27]
Please help, I'm using a texas nspire cx calculator

**Comment by Vogtinator** [comment]
You need ndless.

**Comment by Cheoo21** [comment]
it says 

Error 

Page 1.1 has encountered a error. Please contact the author with the following information.

Line58: cannot add or remove a shape,body,or constraint from this callback.

**Comment by Vogtinator** [comment]
That's https://github.com/ndless-nspire/Ndless/issues/300

**Comment by Cheoo21** [comment]
is there any ways to downgrade versions?
