### ISSUE TITLE
Transforming terrain.png into c byte array

### ISSUE THREAD

**Issue by aviallon** [Vogtinator/crafti#3]
Hello @Vogtinator,
can you tell me how to you convert your png files into byte arrays ? I'm trying to change the textures, but I'm blocked here.
Please, can you help me (or give me a clue ?)

**Comment by Vogtinator** [comment]
You don't need to do that, crafti will use an external texture called ```/documents/ndless/crafti.ppm.tns```, which is terrain.png converted into ppm format.
