### ISSUE TITLE
Can't turn my head. Is that normal?

### ISSUE THREAD

**Issue by FerdinandoPH** [Vogtinator/crafti#7]
I'm trying to turn my head, but I can't. I can move, but not my head. How am I supposed to move it? I tried the arrow pad, but it does not work. I have the ndless 5.2.0, and my calculator is a TI Nspire cx ii cas t.

**Comment by Vogtinator** [comment]
You can use the touchpad as usual or press on it for the cursor.
Can you navigate in the menu using the touchpad keys?

**Comment by FerdinandoPH** [comment]
No. The touchpad does not work at all when using crafti

**Comment by adriweb** [comment]
Right, works perfectly on both my CX II, but it was rebuilt from the source code using the Ndless 5.2 SDK.

**Comment by FerdinandoPH** [comment]
Could you please give me the tns file you used? I don't know how to compile source code yet...

**Comment by adriweb** [comment]
Hmm try this one: [crafti.tns.zip](https://github.com/Vogtinator/crafti/files/5257250/crafti.tns.zip)

But I suppose @Vogtinator could do another release with the updated binary (or just update the release's binary if nothing changed).

**Comment by Vogtinator** [comment]
A rebuild shouldn't be necessary, if that improves the situation that needs to be investigated.

**Comment by FerdinandoPH** [comment]
> Hmm try this one: [crafti.tns.zip](https://github.com/Vogtinator/crafti/files/5257250/crafti.tns.zip)
> 
> But I suppose @Vogtinator could do another release with the updated binary (or just update the release's binary if nothing changed).

Thank you, I will test it ASAP

**Comment by FerdinandoPH** [comment]
[https://drive.google.com/file/d/1o12M34E-RmO-mhetLmM2osq-fhDgDjbr/view?usp=sharing](url)
It didn't work. I have atttached a video of myself trying it and showing the errors

**Comment by Vogtinator** [comment]
Please try this tns: 

[touchpadreadtest.zip](https://github.com/Vogtinator/crafti/files/5257645/touchpadreadtest.zip)

It prints the touchpad values continuously. If you don't touch it, what are the values? Which values change if you touch it (don't click)? Then press a key and it'll print five values, what are those?

**Comment by FerdinandoPH** [comment]
It's 1 AM here, so I will try it tommorow ASAP

**Comment by FerdinandoPH** [comment]
Here is what happens:
1: Whether if I am not touching anything or I'm touching/clicking it, the values are always: 68,b1,30,12,0,0,0,0,0,0,0,0
2: If I try to press a key, it won't do anything or it will force exit the app.
3: If I try to re-enter the app, the calculator will crash

**Comment by Vogtinator** [comment]
Ok, that looks more like a pointer than actual touchpad data values...
Can you download "NspireLogs.zip" and send it to the contact email address of http://ndless.me/?

**Comment by FerdinandoPH** [comment]
Ok.
By the way, I also recorded myself doing this (in case I did something wrong)
https://youtu.be/MtssBFq7aw0

**Comment by FerdinandoPH** [comment]
Done

**Comment by FerdinandoPH** [comment]
This problem is because a fill of Ndless with the n0320ak models.
https://github.com/ndless-nspire/Ndless/issues/236

**Comment by Vogtinator** [comment]
Let's track it there
