### ISSUE TITLE
Calculator crashes after opening crafti for a second time

### ISSUE THREAD

**Issue by FerdinandoPH** [Vogtinator/crafti#8]
Crafti will start up fine the first time you open it, but if you exit the app and try to open it later, the calculator will crash. I have a Ti nspire cx ii cas T with the 5.2 os

**Comment by adriweb** [comment]
Cannot reproduce the issue on my side, CX II-T CAS 5.2 as well. Works fine several times.

Can you try the latest craft version? https://tiplanet.org/modules/archives/download.php?id=61807

**Comment by FerdinandoPH** [comment]
It has the same problem. I even formatted mi calculator to see if that helped.

**Comment by FerdinandoPH** [comment]
https://drive.google.com/file/d/1o12M34E-RmO-mhetLmM2osq-fhDgDjbr/view?usp=sharing
I recorded myself recreating the problem

**Comment by FerdinandoPH** [comment]
This is also a problem with ndless 5.2.0 with the n-0320ak
https://github.com/ndless-nspire/Ndless/issues/236

**Comment by Vogtinator** [comment]
Let's track it there
