### ISSUE TITLE
Cannot transfer not ".tns" files to Calculator

### ISSUE THREAD

**Issue by IntelligentDisaster** [Vogtinator/crafti#9]
Apparently, you cannot transfer non Nspire supported files to a Nspire. Soooo I just spent +1 hr adding".tns"" to the end of all the files. Just letting you know. :) I've also included all the changed files.
[crafti.zip](https://github.com/Vogtinator/crafti/files/5422534/crafti.zip)

**Comment by Vogtinator** [comment]
You only have to transfer the single `crafti.tns` file, the others are just source code and not of any use on the calculator.

So I'm afraid you just wasted some time...

**Comment by IntelligentDisaster** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO :(

**Comment by IntelligentDisaster** [comment]
Thanks for letting me know though :)
